---
- name: Check to see if we can force a failure
  hosts: all
  become: true
  tasks:
    - name: Try writing to the file
      ansible.builtin.lineinfile:
        path: /tmp/application.txt
        line: "{{ new_line_text }}"
      ignore_errors: true
      register: check

    - name: See what failed
      ansible.builtin.debug:
        msg: "{{ ansible_play_hosts_all }} == {{ check.failed }}"

    # - name: Capture broken hosts
    #   ansible.builtin.set_stats:
    #   register: stats_were_set

    # - name: See stats
    #   ansible.builtin.debug:
    #     msg: "{{ stats_were_set }}"
