---
- name: Check to see if we can force a failure
  hosts: all
  become: true
  tasks:
    - name: Try writing to the file
      ansible.builtin.copy:
        dest: /tmp/application.txt
        content: "I am a working application"
      register: check
  post_tasks:
    - name: Pass the failed hosts
      ansible.builtin.set_stats:
        data:
          broken_hosts: "{{ ansible_play_hosts_all | difference(ansible_play_hosts)}}"
      delegate_to: localhost