---
- name: Fix Application
  hosts: "{{ broken_host | default('localhost') }}"
  pre_tasks:
    - name: Ensure needed variables are correct
      ansible.builtin.assert:
        that: broken_host is not 'localhost'
        fail_msg: "There are no broken hosts defined"
        success_msg: "There are broken hosts"
  tasks:
    - name: Execute the fix
      block:
        - name: Make not working file mutable
          ansible.builtin.file:
            path: /tmp/application.txt
            attributes: "-i"

        - name: Fix the application -- STAT!
          ansible.builtin.lineinfile:
            path: /tmp/application.txt
            line: "I am a working application"