---
- name: Create Demo
  hosts: all
  tasks:
    - name: Create working file
      ansible.builtin.lineinfile:
        path: /tmp/application.txt
        line: "I am a working application"
        create: true
      delegate_to: workinghost.bk.lab

    - name: Create not working file
      ansible.builtin.lineinfile:
        path: /tmp/application.txt
        line: "I am not working"
        create: true
      delegate_to: brokenhost.bk.lab

    - name: Make not working file immutable
      ansible.builtin.file:
        path: /tmp/application.txt
        attributes: "+i"
      delegate_to: brokenhost.bk.lab
